- id: '1629160586788'
  alias: LetsEncrypt check
  description: ''
  trigger:
  - platform: time
    at: 04:00
  condition: []
  action:
  - service: hassio.addon_start
    data:
      addon: core_letsencrypt
  mode: single
- id: '1692641386938'
  alias: Washer done
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.washer_washer_machine_state
    from:
    to: stop
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition: []
  action:
  - service: notify.mobile_app_doridians_iphone
    data:
      title: Washer done
      message: Washer done
  mode: single
- id: '1692641441142'
  alias: Dryer done
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.dryer_dryer_machine_state
    from:
    to: stop
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition: []
  action:
  - service: notify.mobile_app_doridians_iphone
    data:
      title: Dryer done
      message: Dryer done
  mode: single
- id: '1692641702034'
  alias: Dishes done
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.dishwasher_wash_completed
    from:
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition: []
  action:
  - service: notify.mobile_app_doridians_iphone
    data:
      title: Dishes done
      message: Dishes done
  mode: single
