- id: "1735978124624"
  alias: LetsEncrypt Check
  description: ""
  triggers:
    - at: 04:00
      trigger: time
  conditions: []
  actions:
    - data:
        addon: core_letsencrypt
      action: hassio.addon_start
  mode: single
