# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
group: !include groups.yaml

# Text to speech
tts:
  - platform: google_translate

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

discovery:
  ignore:
    - dlna_dmr
    - apple_tv

prometheus:

recorder:
  auto_purge: true
  purge_keep_days: 7
  exclude:
    entity_globs:
      - sensor.*_wifi_signal
    entities:
      - sensor.thotmobile_energy_added_sensor
      - device_tracker.thotmobile_location_tracker
      - sensor.cpu_temperature
      - switch.adaptive_lighting_global

sensor:
  - platform: command_line
    name: CPU temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: "{{ value | multiply(0.001) }}"

neato:
  client_id: !secret neato_client_id
  client_secret: !secret neato_client_secret

input_boolean:
  bedroom_ceiling_fan_state:
  office_ceiling_fan_state:
  corner_ceiling_fan_state:

input_number:
  bedroom_ceiling_fan_percentage:
    min: 0
    max: 100
  office_ceiling_fan_percentage:
    min: 0
    max: 100
  corner_ceiling_fan_percentage:
    min: 0
    max: 100

fan:
  - platform: template
    fans:
      bedroom_ceiling_fan:
        friendly_name: "Bedroom Ceiling Fan"
        unique_id: "config_bedroom_ceiling_fan"
        value_template: "{{ states('input_boolean.bedroom_ceiling_fan_state') }}"
        percentage_template: "{{ states('input_number.bedroom_ceiling_fan_percentage') }}"
        turn_on:
          service: script.ceiling_fan_on
          data:
            entity_id: bedroom_ceiling_fan
        turn_off:
          service: script.ceiling_fan_off
          data:
            entity_id: bedroom_ceiling_fan
        set_percentage:
          service: script.ceiling_fan_set_percentage
          data:
            percentage: "{{ percentage }}"
            entity_id: bedroom_ceiling_fan
  - platform: template
    fans:
      office_ceiling_fan:
        friendly_name: "Office Ceiling Fan"
        unique_id: "config_office_ceiling_fan"
        value_template: "{{ states('input_boolean.office_ceiling_fan_state') }}"
        percentage_template: "{{ states('input_number.office_ceiling_fan_percentage') }}"
        turn_on:
          service: script.ceiling_fan_on
          data:
            entity_id: office_ceiling_fan
        turn_off:
          service: script.ceiling_fan_off
          data:
            entity_id: office_ceiling_fan
        set_percentage:
          service: script.ceiling_fan_set_percentage
          data:
            percentage: "{{ percentage }}"
            entity_id: office_ceiling_fan
  - platform: template
    fans:
      corner_ceiling_fan:
        friendly_name: "Corner Ceiling Fan"
        unique_id: "config_corner_ceiling_fan"
        value_template: "{{ states('input_boolean.corner_ceiling_fan_state') }}"
        percentage_template: "{{ states('input_number.corner_ceiling_fan_percentage') }}"
        turn_on:
          service: script.ceiling_fan_on
          data:
            entity_id: corner_ceiling_fan
        turn_off:
          service: script.ceiling_fan_off
          data:
            entity_id: corner_ceiling_fan
        set_percentage:
          service: script.ceiling_fan_set_percentage
          data:
            percentage: "{{ percentage }}"
            entity_id: corner_ceiling_fan
