# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
group: !include groups.yaml

frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

discovery:
  ignore:
    - dlna_dmr
    - apple_tv

prometheus:

recorder:
  auto_purge: true
  purge_keep_days: 7
  exclude:
    entity_globs:
      - sensor.*_wifi_signal
    entities:
      - sensor.thotmobile_energy_added_sensor
      - device_tracker.thotmobile_location_tracker
      - sensor.cpu_temperature
      - switch.adaptive_lighting_global
