# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
group: !include groups.yaml

frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

prometheus:

recorder:
  auto_purge: true
  purge_keep_days: 7
  exclude:
    entity_globs:
      - sensor.*_wifi_signal
    entities:
      - sensor.thotmobile_energy_added_sensor
      - device_tracker.thotmobile_location_tracker
      - sensor.cpu_temperature
      - switch.adaptive_lighting_global

template:
  - sensor:
      - name: "Total Home Power"
        unique_id: total_home_power
        state: "{{ (states('sensor.hot_phase_left_power')|float + states('sensor.hot_phase_right_power')|float) }}"
        unit_of_measurement: "W"
        state_class: measurement

      - name: "Total Home Consumption"
        unique_id: total_home_consumption
        state: "{{ (states('sensor.hot_phase_left_consumption')|float + states('sensor.hot_phase_right_consumption')|float + states('sensor.tesla_wall_connector_energy')|float) }}"
        unit_of_measurement: "Wh"
        state_class: total_increasing

zha:
  device_config:
    f4:b3:b1:ff:fe:f2:22:b6-1:
      type: "switch"
  zigpy_config:
    network:
      channel: 15
      channels: [15]
