# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:

# Individual options represented by default_config
automation: !include automations.yaml
#backup:
#cloud:
config:
counter:
#dhcp:
energy:
frontend:
history:
image:
input_boolean:
input_button:
input_datetime:
input_number:
input_select:
input_text:
logbook:
map:
#media_source:
mobile_app:
#my:
person:
scene: !include scenes.yaml
script: !include scripts.yaml
#ssdp:
stream:
sun:
system_health:
tag:
timer:
usb:
webhook:
#zeroconf:
zone:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

discovery:
  ignore:
    - dlna_dmr
    - apple_tv

prometheus:

recorder:
  auto_purge: true
  purge_keep_days: 7
  exclude:
    entity_globs:
      - sensor.*_wifi_signal
    entities:
      - sensor.thotmobile_energy_added_sensor
      - device_tracker.thotmobile_location_tracker
      - sensor.cpu_temperature
      - switch.adaptive_lighting_global

sensor:
  - platform: command_line
    name: CPU temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: "{{ value | multiply(0.001) }}"

neato:
  client_id: !secret neato_client_id
  client_secret: !secret neato_client_secret
