substitutions:
  type_prefix: "AirGradient"
  type_prefix_host: "airgradient"

packages:
  common: !include common.yaml

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

logger:
  level: DEBUG

i2c:
  sda: D2
  scl: D1
  scan: true
  id: bus_a

bluetooth_proxy:
  active: false

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms

uart:
  - rx_pin: D5
    tx_pin: D6
    baud_rate: 9600
    id: uart_pms5003
  - rx_pin: D4
    tx_pin: D3
    baud_rate: 9600
    id: uart_senseair

sensor:
  - platform: sht3xd
    temperature:
      name: "${friendly_name} Temperature"
    humidity:
      name: "${friendly_name} Humidity"
    address: 0x44
    update_interval: 60s
  - platform: pmsx003
    type: PMSX003
    uart_id: uart_pms5003
    pm_1_0:
      name: "${friendly_name} Particulate Matter <1.0µm Concentration"
      device_class: pm1
      filters:
        - offset: 1
        - median:
            window_size: 60
            send_every: 60
    pm_2_5:
      name: "${friendly_name} Particulate Matter <2.5µm Concentration"
      device_class: pm25
      filters:
        - offset: 1
        - median:
            window_size: 60
            send_every: 60
    pm_10_0:
      name: "${friendly_name} Particulate Matter <10.0µm Concentration"
      device_class: pm10
      filters:
        - offset: 1
        - median:
            window_size: 60
            send_every: 60
  - platform: senseair
    id: senseair_co2_sensor
    uart_id: uart_senseair
    update_interval: 60s
    co2:
      name: "${friendly_name} CO2"
      id: senseair_co2_value

button:
  - platform: template
    name: "${friendly_name} ${type_prefix} Enable ABC"
    disabled_by_default: true
    on_press:
      - senseair.abc_enable: senseair_co2_sensor
  - platform: template
    name: "${friendly_name} ${type_prefix} Disable ABC"
    disabled_by_default: true
    on_press:
      - senseair.abc_disable: senseair_co2_sensor
  - platform: template
    name: "${friendly_name} ${type_prefix} Query ABC Period"
    disabled_by_default: true
    on_press:
      - senseair.abc_get_period: senseair_co2_sensor
  - platform: template
    name: "${friendly_name} ${type_prefix} Force BC"
    disabled_by_default: true
    on_press:
      - senseair.background_calibration: senseair_co2_sensor
  - platform: template
    name: "${friendly_name} ${type_prefix} Query BC Result"
    disabled_by_default: true
    on_press:
      - senseair.background_calibration_result: senseair_co2_sensor
