substitutions:
  type_prefix: "AirGradient"
  type_prefix_host: "airgradient"

packages:
  common: !include common.yaml

esp8266:
  board: d1_mini

i2c:
  sda: D2
  scl: D1
  scan: true
  id: bus_a

uart:
  - rx_pin: D5
    tx_pin: D6
    baud_rate: 9600
    id: uart_pms5003
  - rx_pin: D4
    tx_pin: D3
    baud_rate: 9600
    id: uart_senseair

sensor:
  - platform: sht3xd
    temperature:
      name: "${friendly_name} Temperature"
    humidity:
      name: "${friendly_name} Humidity"
    address: 0x44
    update_interval: 60s
  - platform: pmsx003
    type: PMSX003
    uart_id: uart_pms5003
    pm_1_0:
      name: "${friendly_name} Particulate Matter <1.0µm Concentration"
      filters:
        - median:
            window_size: 60
            send_every: 60
    pm_2_5:
      name: "${friendly_name} Particulate Matter <2.5µm Concentration"
      filters:
        - median:
            window_size: 60
            send_every: 60
    pm_10_0:
      name: "${friendly_name} Particulate Matter <10.0µm Concentration"
      filters:
        - median:
            window_size: 60
            send_every: 60
  - platform: senseair
    id: senseair_co2_sensor
    uart_id: uart_senseair
    co2:
      name: "${friendly_name} CO2"
      id: senseair_co2_value
    update_interval: 60s

button:
  - platform: template
    name: "${friendly_name} ${type_prefix} Enable ABC"
    internal: true
    on_press:
      - senseair.abc_enable: senseair_co2_sensor
  - platform: template
    name: "${friendly_name} ${type_prefix} Disable ABC"
    internal: true
    on_press:
      - senseair.abc_disable: senseair_co2_sensor
  - platform: template
    name: "${friendly_name} ${type_prefix} Query ABC Period"
    internal: true
    on_press:
      - senseair.abc_get_period: senseair_co2_sensor
  - platform: template
    name: "${friendly_name} ${type_prefix} Force BC"
    internal: true
    on_press:
      - senseair.background_calibration: senseair_co2_sensor
  - platform: template
    name: "${friendly_name} ${type_prefix} Query BC Result"
    internal: true
    on_press:
      - senseair.background_calibration_result: senseair_co2_sensor
