substitutions:
  type_prefix: "Athom LED strip"
  type_prefix_host: "athom-led-strip"

packages:
  common: !include common.yaml

esp8266:
  board: esp8285
  framework:
    version: 2.7.4

power_supply:
  - id: relay
    pin: GPIO12

light:
  - platform: fastled_clockless
    pin: GPIO1
    id: leds
    name: "${friendly_name}"
    power_supply: relay
    chipset: WS2812B
    num_leds: 300
    rgb_order: GRB
    restore_mode: ALWAYS_OFF
    effects:
      - addressable_rainbow:
      - addressable_scan:
