packages:
  common-no-wifi: !include common-no-wifi.yaml

external_components:
  - source:
      type: local
      path: components

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: wifi_signal
    name: "${friendly_name} ${type_prefix} WiFi Signal"
    update_interval: 60s
    internal: true
