packages:
  common-nsto-wifi: !include common-no-wifi.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: wifi_signal
    name: "${friendly_name} ${type_prefix} WiFi Signal"
    update_interval: 60s
    internal: true
