substitutions:
  type_prefix: "Humidity switch"
  type_prefix_host: "humidity-switch"

packages:
  common: !include common.yaml

esp8266:
  board: esp8285

logger:
  level: DEBUG

i2c:
  sda: GPIO13
  scl: GPIO4
  scan: true
  id: bus_a

esphome:
  includes:
    - components/hackota/ota.h

ota:
  on_begin:
    then:
      - if:
          condition:
            fan.is_on: relay_fan
          then:
            - lambda: |-
                force_close_ota(id(main_ota));

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      mode:
        input: true
        pullup: true
      inverted: True
    name: "${friendly_name} ${type_prefix} Button"
    internal: true
    on_press:
      - fan.toggle: relay_fan

sensor:
  - platform: aht10
    temperature:
      name: "${friendly_name} ${type_prefix} Temperature"
    humidity:
      name: "${friendly_name} ${type_prefix} Humidity"
    update_interval: 60s

status_led:
  pin:
    number: GPIO12
    inverted: true

output:
  - platform: gpio
    id: led
    pin:
      number: GPIO14
      inverted: true
  - platform: gpio
    id: relay
    pin:
      number: GPIO5

fan:
  - platform: binary
    name: "${friendly_name} ${type_prefix} Fan"
    output: relay
    id: relay_fan
    on_turn_on:
      then:
        - output.turn_on: led
    on_turn_off:
      then:
        - output.turn_off: led
