substitutions:
  type_prefix: "LED strip"
  type_prefix_host: "led-strip"

packages:
  common: !include common.yaml

esp32:
  board: wemos_d1_mini32

wled:

light:
  - platform: partition
    name: "${friendly_name}"
    restore_mode: ALWAYS_OFF
    segments:
      - id: led_strip_1
        from: 0
        to: ${led_max_1}
        reversed: ${led_reverse_1}
      - id: led_strip_2
        from: 0
        to: ${led_max_2}
        reversed: ${led_reverse_2}
      - id: led_strip_3
        from: 0
        to: ${led_max_3}
        reversed: ${led_reverse_3}
      - id: led_strip_4
        from: 0
        to: ${led_max_4}
        reversed: ${led_reverse_4}
    effects:
      - wled:
  - platform: neopixelbus
    type: BRG
    variant: WS2811
    pin: GPIO13
    num_leds: ${led_count_1}
    id: led_strip_1
    internal: true
    method:
      type: esp32_rmt
      channel: 0
  - platform: neopixelbus
    type: BRG
    variant: WS2811
    pin: GPIO23
    num_leds: ${led_count_2}
    id: led_strip_2
    internal: true
    method:
      type: esp32_rmt
      channel: 1
  - platform: neopixelbus
    type: BRG
    variant: WS2811
    pin: GPIO19
    num_leds: ${led_count_3}
    id: led_strip_3
    internal: true
    method:
      type: esp32_rmt
      channel: 2
  - platform: neopixelbus
    type: BRG
    variant: WS2811
    pin: GPIO18
    num_leds: ${led_count_4}
    id: led_strip_4
    internal: true
    method:
      type: esp32_rmt
      channel: 3
