substitutions:
  type_prefix: "LED strip"
  type_prefix_host: "led-strip"

packages:
  common: !include common.yaml

esp32:
  board: wemos_d1_mini32

wled:

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: GPIO21
    name: "${friendly_name}"
    num_leds: ${led_count_1}
    method:
      type: esp32_i2s
      bus: 0
    effects:
      - wled:
