packages:
  sonoff-s31-super: !include sonoff-s31-super.yaml

esphome:
  includes:
    - components/hackota/ota.h

ota:
  on_begin:
    then:
      - if:
          condition:
            switch.is_on: relay
          then:
            - lambda: |-
                esphome::ota::OTAComponent *hota = id(main_ota);
                if ((hota->*result<OTAComponent_client_>::ptr) != nullptr) {
                  (hota->*result<OTAComponent_client_>::ptr)->close();
                }
switch:
  - platform: gpio
    name: "${friendly_name} Relay"
    pin: GPIO12
    id: relay
