packages:
  sonoff-s31-super: !include sonoff-s31-super.yaml

esphome:
  includes:
    - components/hackota/ota.h

ota:
  on_begin:
    then:
      - if:
          condition:
            switch.is_on: relay
          then:
            - lambda: |-
                force_close_ota(id(main_ota));

switch:
  - platform: gpio
    name: "${friendly_name} Relay"
    pin: GPIO12
    id: relay
