substitutions:
  type_prefix: "Uplift"
  type_prefix_host: "uplift"

packages:
  custom: !include common.yaml

esp8266:
  board: d1_mini

uart:
  - rx_pin:
      number: D1
      mode:
        input: true
        pullup: false
        pulldown: false
    baud_rate: 9600
    id: uart_desk
    # debug:
    #   direction: BOTH
    #   dummy_receiver: false
    #   after:
    #     timeout: 5ms
    #   sequence:
    #     - lambda: UARTDebug::log_string(uart::UART_DIRECTION_RX, bytes);
  - rx_pin:
      number: D7
      mode:
        input: true
        pullup: false
        pulldown: false
    baud_rate: 9600
    id: uart_controller
    # debug:
    #   direction: BOTH
    #   dummy_receiver: true
    #   after:
    #     timeout: 5ms
    #   sequence:
    #     - lambda: UARTDebug::log_string(uart::UART_DIRECTION_TX, bytes);

output:
  - platform: gpio
    id: button_bit1
    pin:
      number: D4
      inverted: true
      mode:
        output: true
        open_drain: true
  - platform: gpio
    id: button_bit2
    pin:
      number: D5
      inverted: true
      mode:
        output: true
        open_drain: true
  - platform: gpio
    id: button_bit4
    pin:
      number: D2
      inverted: true
      mode:
        output: true
        open_drain: true
  - platform: gpio
    id: button_m
    pin:
      number: D6
      inverted: true
      mode:
        output: true
        open_drain: true

button:
  - platform: template
    name: "${friendly_name} Profile 1"
    on_press:
      - output.turn_on: button_bit1
      - output.turn_on: button_bit2
      - delay: 100ms
      - output.turn_off: button_bit1
      - output.turn_off: button_bit2
  - platform: template
    name: "${friendly_name} Profile 2"
    on_press:
      - output.turn_on: button_bit4
      - delay: 100ms
      - output.turn_off: button_bit4
  - platform: template
    name: "${friendly_name} Profile 3"
    on_press:
      - output.turn_on: button_bit1
      - output.turn_on: button_bit4
      - delay: 100ms
      - output.turn_off: button_bit1
      - output.turn_off: button_bit4
  - platform: template
    name: "${friendly_name} Profile 4"
    on_press:
      - output.turn_on: button_bit2
      - output.turn_on: button_bit4
      - delay: 100ms
      - output.turn_off: button_bit2
      - output.turn_off: button_bit4

sensor:
  - id: desk_height
    uart_id: uart_desk
    platform: uplift
    name: "${friendly_name} Height"
