substitutions:
  type_prefix: "AirGradient"
  type_prefix_host: "airgradient"

packages:
  common: !include base-common.yaml

esp8266:
  board: d1_mini

i2c:
  sda: D2
  scl: D1
  scan: true
  id: bus_a

uart:
  - rx_pin: D5
    tx_pin: D6
    baud_rate: 9600
    id: uart_pms5003
  - rx_pin: D4
    tx_pin: D3
    baud_rate: 9600
    id: uart_senseair

sensor:
  - platform: sht3xd
    temperature:
      name: "${friendly_name} Temperature"
    humidity:
      name: "${friendly_name} Humidity"
    address: 0x44
    update_interval: 60s
  - platform: pmsx003
    type: PMSX003
    uart_id: uart_pms5003
    pm_1_0:
      name: "${friendly_name} Particulate Matter <1.0µm Concentration"
    pm_2_5:
      name: "${friendly_name} Particulate Matter <2.5µm Concentration"
    pm_10_0:
      name: "${friendly_name} Particulate Matter <10.0µm Concentration"
  - platform: senseair
    uart_id: uart_senseair
    co2:
      name: "${friendly_name} CO2"
    update_interval: 60s
