substitutions:
  friendly_name: "Living Room"
  device_name: "living-room"

packages:
  btproxy: !include base/btproxy.yaml

esp32:
  board: wesp32
  framework:
    type: esp-idf

ethernet:
  type: RTL8201
  mdc_pin: GPIO16
  mdio_pin: GPIO17
  clk_mode: GPIO0_IN
  phy_addr: 0
