substitutions:
  friendly_name: "Main current clamp"
  device_name: "current-clamp-main"

packages:
  custom: !include base/custom.yaml

esp8266:
  board: d1_mini

i2c:
  sda: D2
  scl: D1
  scan: true

ads1115:
  - address: 0x48
    id: ads
    continuous_mode: true

# https://github.com/Mottramlabs/4-Channel-Mains-Current-Sensor/issues/2
# filters:
#   - calibrate_linear:
#       # Measured value of 0 maps to 0A
#       - 0 -> 0
#       # Known load: 2.00A
#       # Value shown in logs: 0.028A
#       - 0.028 -> 4.00

sensor:
  - platform: ads1115
    multiplexer: 'A0_GND'
    gain: 2.048
    internal: true
    id: ads_1

  - platform: ads1115
    multiplexer: 'A1_GND'
    gain: 2.048
    internal: true
    id: ads_2

  - platform: ads1115
    multiplexer: 'A2_GND'
    gain: 2.048
    internal: true
    id: ads_3
  
  - platform: ads1115
    multiplexer: 'A3_GND'
    gain: 2.048
    internal: true
    id: ads_4

  - platform: ct_clamp
    sensor: ads_1
    name: "Hot phase left current"
    id: host_phase_left_current
    update_interval: 10s
    sample_duration: 160ms
    filters:
      - calibrate_linear:
          - 0 -> 0
          - 0.028 -> 4.00

  - platform: ct_clamp
    sensor: ads_2
    name: "Hot phase right current"
    id: host_phase_right_current
    update_interval: 10s
    sample_duration: 160ms
    filters:
      - calibrate_linear:
          - 0 -> 0
          - 0.028 -> 4.00

  - platform: ct_clamp
    sensor: ads_3
    name: "Server rack current"
    id: server_rack_current
    update_interval: 10s
    sample_duration: 160ms
    internal: true
    filters:
      - calibrate_linear:
          - 0 -> 0
          - 0.028 -> 4.00

  - platform: ct_clamp
    sensor: ads_4
    name: "Null current"
    id: null_current
    update_interval: 10s
    sample_duration: 160ms
    internal: true
    filters:
      - calibrate_linear:
          - 0 -> 0
          - 0.028 -> 4.00

  - platform: homeassistant
    entity_id: sensor.dori_pc_voltage
    internal: true
    id: hot_phase_left_voltage

  - platform: homeassistant
    entity_id: sensor.ups_rack_input_voltage
    internal: true
    id: hot_phase_right_voltage

  - platform: template
    name: "Hot phase left power"
    device_class: power
    state_class: measurement
    id: hot_phase_left_power
    unit_of_measurement: W
    update_interval: 10s
    lambda: |-
      float voltage = id(hot_phase_left_voltage).state;
      if (isnan(voltage) || voltage < 10.0) {
        voltage = 120.0;
      }
      return id(host_phase_left_current).state * voltage;

  - platform: template
    name: "Hot phase right power"
    device_class: power
    state_class: measurement
    id: hot_phase_right_power
    unit_of_measurement: W
    update_interval: 10s
    lambda: |-
      float voltage = id(hot_phase_right_voltage).state;
      if (isnan(voltage) || voltage < 10.0) {
        voltage = 120.0;
      }
      return id(host_phase_right_current).state * voltage;

  - platform: total_daily_energy
    name: "Hot phase left consumption"
    restore: false
    power_id: hot_phase_left_power

  - platform: total_daily_energy
    name: "Hot phase right consumption"
    restore: false
    power_id: hot_phase_right_power

time:
  - platform: homeassistant
