substitutions:
    friendly_name: "LED strip Dori Office"
    device_name: "led-strip-dori-office"

packages:
    custom: !include base/custom.yaml

esp32:
    board: wemos_d1_mini32

wled:

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: D2
    num_leds: 300
    name: "Strip 1"
    effects:
      - wled:
