substitutions:
  friendly_name: "Dori RCA switcher"
  device_name: "dori-rca-switcher"

packages:
  custom: !include base/custom.yaml

rp2040:
  board: rpipicow

number:
  - platform: switch_tree
    name: "${friendly_name} Input"
    s1_id: k1
    s2_id: k2
    s3_id: k3
    s4_id: k4
    s5_id: k5
    s6_id: k6
    s7_id: k7
    restore_value: true
    #optimistic: true

switch:
  - id: k1
    name: k1
    restore_mode: DISABLED
    internal: true
    platform: latching_relay
    set_pin: 9
    reset_pin: 8
  - id: k2
    name: k2
    restore_mode: DISABLED
    internal: true
    platform: latching_relay
    set_pin: 5
    reset_pin: 4
  - id: k3
    name: k3
    restore_mode: DISABLED
    internal: true
    platform: latching_relay
    set_pin: 13
    reset_pin: 12
  - id: k4
    name: k4
    restore_mode: DISABLED
    internal: true
    platform: latching_relay
    set_pin: 3
    reset_pin: 2
  - id: k5
    name: k5
    restore_mode: DISABLED
    internal: true
    platform: latching_relay
    set_pin: 7
    reset_pin: 6
  - id: k6
    name: k6
    restore_mode: DISABLED
    internal: true
    platform: latching_relay
    set_pin: 11
    reset_pin: 10
  - id: k7
    name: k7
    restore_mode: DISABLED
    internal: true
    platform: latching_relay
    set_pin: 15
    reset_pin: 14
  - id: k8_
    name: "${friendly_name} Processor In"
    restore_mode: RESTORE_DEFAULT_OFF
    is_assumed_state: false
    platform: latching_relay
    set_pin: 16
    reset_pin: 17
  - id: k9
    name: "${friendly_name} Processor Out"
    restore_mode: RESTORE_DEFAULT_OFF
    is_assumed_state: false
    platform: latching_relay
    set_pin: 19
    reset_pin: 18
