substitutions:
  friendly_name: "BTProxy Living Room"
  device_name: "btproxy-living-room"

packages:
  custom: !include base/custom-no-wifi.yaml

logger:
  baud_rate: 115200
  level: DEBUG

esp32:
  board: wesp32
  framework:
    type: esp-idf

ethernet:
  type: RTL8201
  mdc_pin: GPIO16
  mdio_pin: GPIO17
  clk_mode: GPIO0_IN
  phy_addr: 0

bluetooth_proxy:
  active: true

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true
