substitutions:
    friendly_name: "LED Microscope"
    device_name: "led-microscope"

packages:
    custom: !include base/custom.yaml
    webserver: !include base/webserver.yaml

esp32:
    board: adafruit_qtpy_esp32s2

light:
  - platform: neopixelbus
    type: GRBW
    variant: WS2812
    pin: GPIO35
    num_leds: 40
    name: "${friendly_name} LED"
    default_transition_length: 0s
    restore_mode: ALWAYS_OFF

