substitutions:
    friendly_name: "Dori Office KVM switch"
    device_name: "dori-office-kvm-switch"

packages:
    custom: !include base/custom.yaml

esp8266:
    board: d1_mini

binary_sensor:
  - platform: gpio
    pin: D2 # ADD PULLDOWN
    internal: true
    id: input_toggle_input
    on_press:
      - switch.turn_on: input_toggle_output
  - platform: gpio
    pin:
      number: D6
      inverted: true
    name: "${friendly_name} current input"
    id: input_display_input
    on_press:
      - output.turn_on: input_display_output
    on_release:
      - output.turn_off: input_display_output

output:
  - platform: gpio
    pin:
      number: D1
      inverted: true
    id: input_display_output

button:
  - platform: template
    name: "${friendly_name} switch to 1"
    on_press:
      - if:
          condition:
            binary_sensor.is_on: input_display_input
          then:
            - switch.turn_on: input_toggle_output
  - platform: template
    name: "${friendly_name} switch to 2"
    on_press:
      - if:
          condition:
            binary_sensor.is_off: input_display_input
          then:
            - switch.turn_on: input_toggle_output

switch:
  - platform: gpio
    pin:
      number: D5
      inverted: false
    id: input_toggle_output
    name: "Input toggle"
    on_turn_on:
      - delay: 1000ms
      - switch.turn_off: input_toggle_output
