substitutions:
    friendly_name: "Garage door"
    device_name: "garage-door"

packages:
    custom: !include base/custom.yaml

esp8266:
    board: esp8285

binary_sensor:
    - platform: gpio
      name: "${friendly_name} Contact"
      device_class: garage_door
      id: contact
      pin:
        number: GPIO4
        inverted: true
      filters:
          - delayed_on: 20ms

    - platform: gpio
      name: "${friendly_name} Button"
      internal: true
      pin:
        number: GPIO14
        mode: INPUT_PULLUP
        inverted: true

switch:
    - platform: gpio
      pin: GPIO5
      name: "${friendly_name} Relay"
      id: relay
      internal: true
      restore_mode: ALWAYS_OFF
      on_turn_on:
          - light.turn_on: wifi_led
          - delay: 1s
          - switch.turn_off: relay
          - light.turn_off: wifi_led

light:
    - platform: status_led
      name: "${friendly_name} Status LED"
      id: wifi_led
      pin: GPIO12
      internal: true

cover:
    - platform: template
      device_class: garage
      name: "${friendly_name}"
      lambda: "return id(contact).state ? COVER_OPEN : COVER_CLOSED;"
      open_action:
          - switch.turn_on: relay
      stop_action:
          - switch.turn_on: relay
      close_action:
          - switch.turn_on: relay
