substitutions:
    friendly_name: "Shaving mirror"
    device_name: "shaving-mirror"

packages:
    custom: !include base/custom.yaml

esp8266:
    board: d1_mini

output:
  - platform: esp8266_pwm
    pin: D5
    frequency: 1000 Hz
    id: light_output

light:
  - platform: monochromatic
    output: light_output
    id: light_entity
    name: "${friendly_name} Light"

binary_sensor:
  - platform: gpio
    pin:
      number: D1
      mode:
        input: true
        pullup: false
      inverted: false
    internal: true
    id: touch_sensor
    filters:
      delayed_off: 100ms
    on_click:
      then:
        - light.toggle: light_entity
