substitutions:
    friendly_name: "Dori Office Ceiling Strip"
    device_name: "dori-office-ceiling"
    led_count_1: "100"
    led_max_1: "99"
    led_reverse_1: "false"
    led_count_2: "50"
    led_max_2: "49"
    led_reverse_2: "true"

logger:
    baud_rate: 115200

packages:
    custom: !include base/led-strip-2-wired.yaml
